/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Activities: typeof import('./src/components/Index/Activities.vue')['default']
    Book: typeof import('./src/components/Book/Book.vue')['default']
    BookCard: typeof import('./src/components/Book/BookCard.vue')['default']
    BookMenu: typeof import('./src/components/Book/BookMenu.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Index: typeof import('./src/components/Index/Index.vue')['default']
    IndexCard: typeof import('./src/components/Index/IndexCard.vue')['default']
    Message: typeof import('./src/components/Message/Message.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sender: typeof import('./src/components/Message/Sender.vue')['default']
    ShoppingCard: typeof import('./src/components/ShoppingCard/ShoppingCard.vue')['default']
    Sidebar: typeof import('./src/components/Book/Sidebar.vue')['default']
    Swipper: typeof import('./src/components/Index/Swipper.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
    TAvatar: typeof import('tdesign-mobile-vue')['Avatar']
    TBadge: typeof import('tdesign-mobile-vue')['Badge']
    TCard: typeof import('tdesign-mobile-vue')['Card']
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TDivider: typeof import('tdesign-mobile-vue')['Divider']
    TDropdownItem: typeof import('tdesign-mobile-vue')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-mobile-vue')['DropdownMenu']
    TImage: typeof import('tdesign-mobile-vue')['Image']
    TRate: typeof import('tdesign-mobile-vue')['Rate']
    TSideBar: typeof import('tdesign-mobile-vue')['SideBar']
    TSideBarItem: typeof import('tdesign-mobile-vue')['SideBarItem']
    TSwiper: typeof import('tdesign-mobile-vue')['Swiper']
    TSwiperItem: typeof import('tdesign-mobile-vue')['SwiperItem']
    TTabBar: typeof import('tdesign-mobile-vue')['TabBar']
    TTabBarItem: typeof import('tdesign-mobile-vue')['TabBarItem']
    TTabPanel: typeof import('tdesign-mobile-vue')['TabPanel']
    TTabs: typeof import('tdesign-mobile-vue')['Tabs']
    TTag: typeof import('tdesign-mobile-vue')['Tag']
    User: typeof import('./src/components/User/User.vue')['default']
  }
}
